name: Deploy Fastify App

on:
  push:
    branches:
      - 'release/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login ke Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build dan Push Image Fastify
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fastify-app:latest


      - name: Deploy with Docker
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            MAX_RETRIES=3
            COUNT=0
            SUCCESS=0

            while [ $COUNT -lt $MAX_RETRIES ]; do
              docker-compose pull --quiet && \
              docker-compose down --remove-orphans && \
              docker-compose up -d --force-recreate --wait && \
              docker image prune -f && SUCCESS=1 && break
              
              COUNT=$((COUNT+1))
              echo "Retrying deployment... Attempt $COUNT"
              sleep 5
            done

            if [ $SUCCESS -eq 0 ]; then
              echo "Deployment failed after $MAX_RETRIES attempts."
              exit 1
            fi