name: Deploy Fastify App (Build and Pull)

on:
  push:
    branches:
      - 'release/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Salin docker-compose.yml ke Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: docker-compose.yml
          target: /home/${{ secrets.SSH_USER }}/fastify-app/

      - name: Deploy dengan Docker Compose di Server (Build dan Pull)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/fastify-app
            docker compose down
            docker compose pull
            docker compose up -d --build