name: Deploy to beta server

on:
  push:
    branches:
      - release/**

env:
  IMAGE_NAME: btk-fastify-gen
  REGISTRY: ghcr.io
  GHCR_IMAGE: ghcr.io/thera-data-solution/btk-fastify-gen:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.GHCR_IMAGE }}


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: prod
    timeout-minutes: 15
    steps:
      - name: Deploy with Docker
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_SECRET }}
          script: |
            cd btk-fastify-gen

            docker compose pull
            docker compose down

            docker compose up -d

            docker image prune -f
